//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.administradorxsucursal = new HashSet<administradorxsucursal>();
            this.empleadoxcaja = new HashSet<empleadoxcaja>();
            this.factura = new HashSet<factura>();
        }
    
        public int cedula { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string senas { get; set; }
        public System.DateTime fechanacimiento { get; set; }
        public string contrasena { get; set; }
        public bool activo { get; set; }
        public string sucursal { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<administradorxsucursal> administradorxsucursal { get; set; }
        public virtual ICollection<empleadoxcaja> empleadoxcaja { get; set; }
        public virtual ICollection<factura> factura { get; set; }
        public virtual rol rol1 { get; set; }
        public virtual sucursal sucursal1 { get; set; }
    }
}
