//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicamento
    {
        public medicamento()
        {
            this.medicamentoxfactura = new HashSet<medicamentoxfactura>();
            this.medicamentoxsucursal = new HashSet<medicamentoxsucursal>();
        }
    
        public string nombre { get; set; }
        public int precio { get; set; }
        public bool prescripcion { get; set; }
        public bool activo { get; set; }
        public string proveedor { get; set; }
    
        public virtual ICollection<medicamentoxfactura> medicamentoxfactura { get; set; }
        public virtual ICollection<medicamentoxsucursal> medicamentoxsucursal { get; set; }
        public virtual proveedor proveedor1 { get; set; }
    }
}
