//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicamentoxsucursal
    {
        public string medicamento { get; set; }
        public string sucursal { get; set; }
        public int cantidad { get; set; }
        public int stockminimo { get; set; }
        public int stockpromedio { get; set; }
        public bool activo { get; set; }
    
        public virtual medicamento medicamento1 { get; set; }
        public virtual sucursal sucursal1 { get; set; }
    }
}
