//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.factura = new HashSet<factura>();
            this.padecimiento = new HashSet<padecimiento>();
            this.telefonoxcliente = new HashSet<telefonoxcliente>();
            this.pedido = new HashSet<pedido>();
        }
    
        public int cedula { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string senas { get; set; }
        public System.DateTime fechanacimiento { get; set; }
        public string contrasena { get; set; }
        public int prioridad { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<factura> factura { get; set; }
        public virtual ICollection<padecimiento> padecimiento { get; set; }
        public virtual ICollection<telefonoxcliente> telefonoxcliente { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
