//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class padecimiento
    {
        public int cliente { get; set; }
        public string padecimiento1 { get; set; }
        public int ano { get; set; }
        public bool activo { get; set; }
    
        public virtual cliente cliente1 { get; set; }
    }
}
