//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public sucursal()
        {
            this.administradorxsucursal = new HashSet<administradorxsucursal>();
            this.caja = new HashSet<caja>();
            this.empleado = new HashSet<empleado>();
            this.medicamentoxsucursal = new HashSet<medicamentoxsucursal>();
            this.pedido = new HashSet<pedido>();
        }
    
        public string nombre { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string senas { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
        public string compania { get; set; }
    
        public virtual ICollection<administradorxsucursal> administradorxsucursal { get; set; }
        public virtual ICollection<caja> caja { get; set; }
        public virtual compania compania1 { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual ICollection<medicamentoxsucursal> medicamentoxsucursal { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
