//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaProyecto2BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compania
    {
        public compania()
        {
            this.sucursal = new HashSet<sucursal>();
        }
    
        public string nombre { get; set; }
        public string sede { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<sucursal> sucursal { get; set; }
    }
}
