//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaProyecto2BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.medicamentoxpedido = new HashSet<medicamentoxpedido>();
        }
    
        public int numero { get; set; }
        public string sucursal { get; set; }
        public int cliente { get; set; }
        public bool activo { get; set; }
    
        public virtual cliente cliente1 { get; set; }
        public virtual ICollection<medicamentoxpedido> medicamentoxpedido { get; set; }
        public virtual sucursal sucursal1 { get; set; }
    }
}
