//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoBaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public caja()
        {
            this.factura = new HashSet<factura>();
            this.empleadoxcaja = new HashSet<empleadoxcaja>();
        }
    
        public int id { get; set; }
        public bool activo { get; set; }
        public string sucursal { get; set; }
    
        public virtual ICollection<factura> factura { get; set; }
        public virtual sucursal sucursal1 { get; set; }
        public virtual ICollection<empleadoxcaja> empleadoxcaja { get; set; }
    }
}
