//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoBaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleadoxcaja
    {
        public int empleado { get; set; }
        public int caja { get; set; }
        public System.DateTime fechainicio { get; set; }
        public System.DateTime fechafinal { get; set; }
        public System.TimeSpan horainicio { get; set; }
        public System.TimeSpan horafinal { get; set; }
        public int efectivoinicial { get; set; }
        public int efectivofinal { get; set; }
        public bool activo { get; set; }
    
        public virtual caja caja1 { get; set; }
        public virtual empleado empleado1 { get; set; }
    }
}
